Updated readme and github workflow

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -26,7 +26,6 @@ jobs:
     name: Cypress - ${{ matrix.name }}
 
     runs-on: ubuntu-latest
-
     timeout-minutes: 15
 
     strategy:
@@ -79,15 +78,7 @@ jobs:
         env:
           CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
 
-      # 5. Rename report file
-      - name: Rename report file
-        if: always()
-        run: |
-          if [ -f cypress/reports/.jsons/mochawesome.json ]; then
-            mv cypress/reports/.jsons/mochawesome.json cypress/reports/.jsons/mochawesome-${{ matrix.name }}.json
-          fi
-
-      # 6. Upload Mochawesome JSON
+      # 5. Upload Mochawesome JSON
       - name: Upload Mochawesome JSON
         if: always()
         uses: actions/upload-artifact@v4
@@ -98,7 +89,7 @@ jobs:
           if-no-files-found: warn
           retention-days: 30
 
-      # 7. Upload Cypress screenshots
+      # 6. Upload Cypress screenshots
       - name: Upload Cypress screenshots
         if: always()
         uses: actions/upload-artifact@v4
@@ -108,7 +99,7 @@ jobs:
           if-no-files-found: ignore
           retention-days: 30
 
-      # 8. Upload Cypress videos
+      # 7. Upload Cypress videos
       - name: Upload Cypress videos
         if: always()
         uses: actions/upload-artifact@v4
@@ -158,26 +149,51 @@ jobs:
           pattern: mochawesome-*
           path: cypress/reports/jsons
 
-      # 5. Merge Mochawesome JSON
+      # 5. Collect JSON reports
+      - name: Collect JSON reports
+        run: |
+          mkdir -p cypress/reports/merged-json
+          counter=0
+          while IFS= read -r file; do
+            counter=$((counter + 1))
+            cp "$file" \
+              "cypress/reports/merged-json/report_${counter}.json"
+          done < <(
+            find cypress/reports/jsons \
+              -type f \
+              -name "*.json"
+          )
+      # 6. Merge Mochawesome JSON
       - name: Merge Mochawesome JSON
-        run: npx mochawesome-merge "cypress/reports/jsons/**/mochawesome-*.json" -o cypress/reports/mochawesome.json
-
-      # 6. Generate HTML report
+        run: |
+          npx mochawesome-merge \
+            "cypress/reports/merged-json/*.json" \
+            -o cypress/reports/mochawesome.json
+          
+          if [ ! -f cypress/reports/mochawesome.json ]; then
+            echo "❌ Error: Merged report not created"
+            exit 1
+          fi
+          echo "✅ Merge successful"
+      # 7. Generate HTML report
       - name: Generate HTML report
-        run: npx marge cypress/reports/mochawesome.json -f index -o cypress/reports/html
-
-      # 7. Setup GitHub Pages
+        run: |
+          npx marge \
+            cypress/reports/mochawesome.json \
+            -f index \
+            -o cypress/reports/html
+      # 8. Configure GitHub Pages
       - name: Setup GitHub Pages
         uses: actions/configure-pages@v5
 
-      # 8. Upload report to GitHub Pages
+      # 9. Upload report to GitHub Pages
       - name: Upload GitHub Pages artifact
         uses: actions/upload-pages-artifact@v4
         with:
           name: github-pages
           path: cypress/reports/html
 
-      # 9. Deploy report to GitHub Pages
+      # 10. Deploy report to GitHub Pages
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
